### ISSUE TITLE
Issue with Backpack 4.1

### ISSUE THREAD

**Issue by bedoz** [DigitallyHappy/toggle-field-for-backpack#2]
Hi Cristian,
Can you fix inc.field_wrapper_attributes issue to bring compatibility with Backpack 4.1?
Can you also fix composer issue:
Deprecation Notice: Class DigitallyHappy\ToggleFieldForBackpack\AddonServiceProvider located in ./vendor/digitallyhappy/toggle-field-for-backpack/src/addonServiceProvider.php does not comply with psr-4 autoloading standard. It will
not autoload anymore in Composer v2.0. in phar:///mnt/c/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201

I think these fix are really quick.
Thank you very much.
Alex

**Comment by tabacitu** [comment]
Thanks for the heads-up @bedoz . Just pushed an update that offers compatibility with Backpack 4.1 - make sure you require version 2 of this package.

Haven't gotten to look at the Composer v2 deprecation notice yet - I'll take a look when I have the time.

Cheers!

**Comment by bedoz** [comment]
@tabacitu the Composer v2 deprecation is really simple you can't use namespace with files and class name that are different, the issue I think is that addonServiceProvider.php use class AddonServiceProvider, maybe the issue is that php file must be renamed to AddonServiceProvider.php

**Comment by tabacitu** [comment]
Yeah but you see @bedoz - that file has been renamed a while ago, it's `AddonServiceProvider.php`, not `addonServiceProvider.php`, but you're still getting the deprecation notice - which is weird 😄 I've bumped the version to 2.0 for the update above (support for Backpack 4.1) - I'm wondering if you're going to get the deprecation notice again this time... Please let me know.

**Comment by bedoz** [comment]
No more isssue i see, it takes the right name. Thank you

**Comment by tabacitu** [comment]
Excellent! Thanks for raising the issue and following up @bedoz ! Also for the testimonial - much appreciated 😄 🥳
