### ISSUE TITLE
Cannot default to true

### ISSUE THREAD

**Issue by adrienne** [DigitallyHappy/toggle-field-for-backpack#9]
adding `'default' => true` into the array for the field does nothing.

**Comment by promatik** [comment]
Hi @adrienne!

I was able to set the default to true, by doing `'default' => true,`.

`'default' => true,`
<img width="251" alt="image" src="https://user-images.githubusercontent.com/1838187/175783798-886334b4-e329-4c54-a0a1-651f82976ace.png">

`'default' => false,`
<img width="272" alt="image" src="https://user-images.githubusercontent.com/1838187/175783784-3c3313a3-0dea-496a-9a81-315ed7445d5d.png">

Can you please confirm your issue? I assume you are talking about the create operation.

**Comment by tabacitu** [comment]
Jumping in - since we can't reproduce I'm going to close this. But @adrienne please come back with more details about the circumstances where this happens and we'll gladly reopen the issue and work together towards a fix.

Cheers!
